# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f7f14b0f69172c5ba13ced3f4df67cf0e42a4efd5a98fe6b736b0c5df16006d8f2e7ad3ed6a87bf906684d1996c578722eec070c66893916aca3512c02a7f50

test:
  secret_key_base: 328e29bb4ac0f811a5e2a6f2193aa3db39fca1e3df435f7b40a8e4862c75212a2ed5a23213f49f2e59fb4563b9a2e6b2aa2223ff0195ca49ea83f55bf859d955

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
