# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70b4fec1588e36d5b73d0c2ddd586dda21244663ca1400e3e77f367532871a271889c2ed57ebfe79ba87b1ab5d5052ca7e22efe9c27a2b658d26d54baf9bcf25

test:
  secret_key_base: 88801ac27f7f19af43b29675b2c28c7578e9fa6c76a189f03ec481df69c2a4a19bff32ca2a53914c5a8897aa79cd46e144e45fa7278c2280c659dce4b055b4c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
